apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-httpd
  name: test-httpd
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test-httpd
  template:
    metadata:
      labels:
        app: test-httpd
    spec:
      containers:
        - image: httpd:alpine3.20
          name: httpd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
